/root/.pyenv/versions/3.10.16/bin/python3: can't open file '/root/data/qiwei/chatgpt-on-wechat/channel/wechatcom/app.py': [Errno 2] No such file or directory
/root/.pyenv/versions/3.10.16/bin/python3: can't open file '/root/data/qiwei/chatgpt-on-wechat/channel/wechatcom/app.py': [Errno 2] No such file or directory
/root/.pyenv/versions/3.10.16/bin/python3: can't open file '/root/data/qiwei/chatgpt-on-wechat/channel/wechatcom/app.py': [Errno 2] No such file or directory
/root/.pyenv/versions/3.10.16/bin/python3: can't open file '/root/data/qiwei/chatgpt-on-wechat/channel/wechatcom/app.py': [Errno 2] No such file or directory
